### ISSUE TITLE
NullPointerException when running the Jenkins plugin

### ISSUE THREAD

**Issue by rodikal** [tomasbjerre/violation-comments-to-bitbucket-server-lib#1]
Hi,

I'm getting a `NullPointerException` when running the Jenkins plugin on an Pull Request that contains a deleted file. I'm using BitBucket Server  v4.4.1

```
java.lang.NullPointerException
	at se.bjurr.violations.comments.bitbucketserver.lib.BitbucketServerCommentsProvider.shouldComment(BitbucketServerCommentsProvider.java:127)
	at se.bjurr.violations.comments.bitbucketserver.lib.BitbucketServerCommentsProvider.shouldComment(BitbucketServerCommentsProvider.java:121)
	at se.bjurr.violations.comments.lib.CommentsCreator.filterChanged(CommentsCreator.java:114)
	at se.bjurr.violations.comments.lib.CommentsCreator.<init>(CommentsCreator.java:41)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:25)
	at se.bjurr.violations.comments.bitbucketserver.lib.ViolationCommentsToBitbucketServerApi.toPullRequest(ViolationCommentsToBitbucketServerApi.java:113)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.doPerform(JvctbPerformer.java:95)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:162)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:149)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.jvctsPerform(JvctbPerformer.java:149)
	at org.jenkinsci.plugins.jvctb.ViolationsToBitbucketServerRecorder.perform(ViolationsToBitbucketServerRecorder.java:61)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1743)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

**Comment by tomasbjerre** [comment]
This should be fixed in version 1.42 of the Jenkins plugin! Open issue again if any problems.
