### ISSUE TITLE
Paths with spaces fail

### ISSUE THREAD

**Issue by ricksmt** [tomasbjerre/violation-comments-to-bitbucket-server-lib#2]
## Issue
I'm trying to leverage the [Violation Comments to Bitbucket Server Jenkins plugin](https://github.com/jenkinsci/violation-comments-to-stash-plugin). I got a minimal setup working for one project, but on another I'm seeing this error (names changed to protect the innocent):

```
java.io.IOException: Server returned HTTP response code: 505 for URL: https://my-bitbucket.com/rest/api/1.0/projects/PR/repos/my-web-service/pull-requests/1/comments?path=MyWebService/Service References/SomeService/Reference.cs&limit=999999
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerInvoker.invokeUrl(BitbucketServerInvoker.java:47)
Caused: java.lang.RuntimeException: Error calling:
https://my-bitbucket.com/rest/api/1.0/projects/PR/repos/my-web-service/pull-requests/1/comments?path=MyWebService/Service References/SomeService/Reference.cs&limit=999999
GET
null
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerInvoker.invokeUrl(BitbucketServerInvoker.java:56)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.invokeAndParse(BitbucketServerClient.java:51)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.pullRequestComments(BitbucketServerClient.java:81)
	at se.bjurr.violations.comments.bitbucketserver.lib.BitbucketServerCommentsProvider.getComments(BitbucketServerCommentsProvider.java:80)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:47)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:26)
	at se.bjurr.violations.comments.bitbucketserver.lib.ViolationCommentsToBitbucketServerApi.toPullRequest(ViolationCommentsToBitbucketServerApi.java:113)
```
## Conjecture
Based on some StackOverflow stuff like [this](https://stackoverflow.com/a/4185926/1680677), I believe the issue is that spaces in the path are not URL encoded. If I try the URL directly in Chrome, the space is automatically encoded and I get a 200 response.

It seems it'll be impossible for me to work around the issue since Service References is a standard .NET folder for, well, referencing services. I tried filtering it out, but to no avail.

**Comment by tomasbjerre** [comment]
Releasing a fix now. Open issue again if not working.
