### ISSUE TITLE
Connection refused exception though credentials 

### ISSUE THREAD

**Issue by stoesselt** [tomasbjerre/violation-comments-to-bitbucket-server-lib#3]
Hi, execution of the violation comments to bitbucket server plug-in in a Jenkins pipeline project produces the following output:
```
---
--- Jenkins Violation Comments to Bitbucket Server ---
---
bitbucketServerUrl: https://SERVER_URL/
projectKey: P2T
repoSlug: code
pullRequestId: 7
credentialsId: true
createSingleFileComments: true
createCommentWithAllSingleFileComments: false
commentOnlyChangedContent: false
commentOnlyChangedContentContext: 0
minSeverity: INFO
keepOldComments: false
cpplint with pattern cpplint-result\.xml
Pull request: 7
Workspace: /srv/www/jenkins/workspace/code_PR-7-7S7CYR323YORU65XFMRGB5AFWUTKJ5IHOVX2WIB2M4IM6EQQZRXA
Found 0 violations from ViolationConfig [pattern=cpplint-result\.xml, reporter=cpplint, parser=CPPLINT].
PR: P2T/code/7 on https://SERVER_URL/
java.lang.RuntimeException: Error calling:
https://SERVER_URL/rest/api/1.0/projects/P2T/repos/code/pull-requests/7/changes?limit=999999
GET
null
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerInvoker.doInvokeUrl(BitbucketServerInvoker.java:88)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerInvoker.invokeUrl(BitbucketServerInvoker.java:51)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.doInvokeUrl(BitbucketServerClient.java:97)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.invokeAndParse(BitbucketServerClient.java:69)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerClient.pullRequestChanges(BitbucketServerClient.java:80)
	at se.bjurr.violations.comments.bitbucketserver.lib.BitbucketServerCommentsProvider.getFiles(BitbucketServerCommentsProvider.java:106)
	at se.bjurr.violations.comments.lib.CommentsCreator.<init>(CommentsCreator.java:42)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:25)
	at se.bjurr.violations.comments.bitbucketserver.lib.ViolationCommentsToBitbucketServerApi.toPullRequest(ViolationCommentsToBitbucketServerApi.java:133)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.doPerform(JvctbPerformer.java:137)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:220)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer$1.invoke(JvctbPerformer.java:208)
	at hudson.FilePath.act(FilePath.java:1009)
	at hudson.FilePath.act(FilePath.java:987)
	at org.jenkinsci.plugins.jvctb.perform.JvctbPerformer.jvctsPerform(JvctbPerformer.java:207)
	at org.jenkinsci.plugins.jvctb.ViolationsToBitbucketServerRecorder.perform(ViolationsToBitbucketServerRecorder.java:66)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at se.bjurr.violations.comments.bitbucketserver.lib.client.BitbucketServerInvoker.doInvokeUrl(BitbucketServerInvoker.java:74)
	... 25 more
```

I use the same credentials and URL earlier in that Jenkinsfile for checking out the git repository, so I would guess that it should work. I used the Pipeline Syntax generator for the Jenkinsfile:

```
ViolationsToBitbucketServer(
[
	bitbucketServerUrl: 'https://SERVER_URL/',
	createSingleFileComments: true,
	credentialsId: 'CREDENTIALS_ID',
	projectKey: 'P2T',
	pullRequestId: env.CHANGE_ID,
	repoSlug: 'code',
	violationConfigs: [
	[
		parser: 'CPPLINT', pattern: 'cpplint-result\\.xml', reporter: 'cpplint'
	]]
])
```

Can you help?

**Comment by tomasbjerre** [comment]
Are you sure it is not being blocked by a firewall?

**Comment by tomasbjerre** [comment]
You do checkout with https?

**Comment by tomasbjerre** [comment]
Are you using nodes when building? Perhaps cloning on one node and using the plugin on another.

**Comment by stoesselt** [comment]
Actually, no. The whole pipeline is executed on the same server. I check out with the configuration above, which works. Then I do the building and testing stuff and want to report the findings with the same credentials. 

Additionally, SERVER_URL has valid public certificate.

When I try to open the link manually with curl, providing cretentials, I get an valid response.

**Comment by tomasbjerre** [comment]
Curl from tje jenkins server or from another machine?
What version of bitbucket server and what version of the plugin?

**Comment by stoesselt** [comment]
Yeah sorry, curl from the jenkins server.

Atlassian Bitbucket v5.7.1
Jenkins ver. 2.107.2
Jenkins Violation Comments to Bitbucket Server Plugin 1.70

**Comment by tomasbjerre** [comment]
Still sounds like a firewall issue to me. https://stackoverflow.com/questions/6876266/java-net-connectexception-connection-refused

**Comment by stoesselt** [comment]
Hi, I still have the problem and now some more time to cope with it. For recapitulation:
* I still have the same configuration of the ViolationsToBitbucketServer as in the first post.
* The credentials I use are the same during checkout and for ViolationsToBitbucketServer.
* The checkout indeed works, connection of ViolationsToBitbucketServer is refused.
* Manually calling the URL where the exception occurs with curl on the jenkins server and providing the same user and password information, return with correct data without an error. 
* Without providing credentials I also get a response, which is of course reasonable: 

> "You are not permitted to access this Resource","exceptionName":"com.atlassian.bitbucket.AuthorisationException"
* However, the problem with the plugin is deeper, not a problem of incorrect authentication, because we get no response at all.
* You said it likely is a firewall problem, but then why does the checkout and the manual curl call work? The big question is what is the difference in connecting to the Bitbucket server between the GitSCM plug-in and this plug-in.
** Only a guess: Maybe the timeout for the connection is too small?

**Comment by stoesselt** [comment]
OK, first I had a look to your implementation how to establish the connection. Especially, at `/src/main/java/se/bjurr/violations/comments/bitbucketserver/lib/client/BitbucketServerInvoker.java` lines 63 to 74. 

Then I had a look to the Jenkins Stash Notifier plug-in, which also works in my case. There in `/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java` I found the `configureProxy()` function and now I know the problem I think.

In order to have Internet access I had to setup a Proxy on the Jenkins server, which I configured both for Jenkins Server and my shell. And that's it. My shell and the GitSCM as well as the Stash Notifier will consider the Proxy while this plug-in does not. And this is why the url could not be resolved and nothing reponds we lead to the Exception.

So my question to you, can you introduce the consideration of a proxy in the Jenkins configuration in this library or the corresponding Jenkins plug-in?

**Comment by stoesselt** [comment]
Hi, do you already plan an update? If not, would it be okay, if I try to prepare a pull request for it?

**Comment by tomasbjerre** [comment]
It is on my todo-list. But if you can provide a PR, that is great!

Just make sure this library does not depend on anything Jenkins-related.

And after that another change is needed in the Jenkins plugin. To gather proxy information from Jenkins and use the feature, developed in this library, to apply that config.

**Comment by stoesselt** [comment]
I am unfamilar with Java development, can you give me a quick guide, how I can setup the development environment for contribution? What should I do with the travis.yml and the gradlew?

Which IDE is best to use for this development?
Do I need to setup a project myself, is it somehow automated (by Gradle or something)?

**Comment by stoesselt** [comment]
Ok, using gradlew.bat resulted in having Eclipse project files, so these questions are done.

I would like to know your preferred solution:
1. Usage of java built-in dependencies (java.net.xxx). The problem here is that we need to set the default Authenticator (which is valid for the whole system?). [Stackoverflow: How do I make HttpUrlConnection use a proxy](https://stackoverflow.com/questions/1432961/how-do-i-make-httpurlconnection-use-a-proxy)
2. Usage of OkHttp 3.10. [Stackoverflow: OkHttpClient proxy authentication how to](https://stackoverflow.com/questions/35554380/okhttpclient-proxy-authentication-how-to)
3. Usage of Apache Http packages as used in Stash Notifier (search for configureProxy()) [StashNotifier](https://github.com/jenkinsci/stashnotifier-plugin/blob/release/1.x/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java)

**Comment by stoesselt** [comment]
Hi, I have prepared an implementation for a pull request. It seems that I have no permission to push to your repo. If I understand Github correctly (I am new to it), I could fork and create a pull request after that. Is this your preferred way or do you give me the permission to contribute to your repo?

**Comment by tomasbjerre** [comment]
Yes. Fork and push to the fork. Then open a PR.

**Comment by tomasbjerre** [comment]
The Jenkins plugin is released with this now. As version 1.73. Will be available in Jenkins update site within a few hours.
